config/routes.rb
SampleApp::Application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  root 'static_pages#home'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save {self.email=email.downcase}
  before_create :create_remember_token

  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\_.]+@[a-z\d\_.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, length: { minimum: 8}

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  # Before filters

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Poofer (c)2014 by Dzambala
  </small>
  <nav>
    <ul>
      <li><%= link_to "O nas", about_path %></li>
      <li><%= link_to "Kontakt", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "Poofer", '#', id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Strona domowa", root_path %></li>
          <li><%= link_to "Pomoc", help_path%></li>

          <% if signed_in? %>
              <li><%= link_to "Użytkownicy", users_path %></li>
              <p class="navbar-text"><span class="glyphicon glyphicon-user"></span><%= @current_user.name %></p>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-cog"> mójPoofer <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "Mój profil", current_user %></li>
                  <li><%= link_to "Zmień dane", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Wyloguj się", signout_path, method: "delete" %>
                  </li>
                </ul>
          <% else %>
              <li><%= link_to "Zaloguj się", signin_path %></li>
              <li><%= link_to "Nie masz konta? Zarejestruj się", signup_path, class: "btn navbar-btn btn-warning" %></li>
          <% end %>
        </ul>
      </nav>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>Ruby on Rails Tutorial Sample App | <%= yield(:title)%></title>
      <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
      <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
      <%= csrf_meta_tags %>
      <%= render 'layouts/shim' %>
    </head>
    <body>
      <%= render 'layouts/header' %>
        <div class="container">
          <% flash.each do |key, value| %>
              <div class="alert alert-<%= key %>"><%= value %></div>
          <% end %>
          <%= yield %>
          <%= render 'layouts/footer'%>
          <%= debug(params) if Rails.env.development? %>
        </div>
    </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>Sample App</h1>
<p>
  This is the <%= yield(:title) %> page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Sample App</h1>
<p>
  This is the <%= yield(:title) %> page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Poofer') %>
<div class="jumbotron">
  <h1>Poofer</h1>
  <h2>POszukuję. OFERuję. </h2>
  <h3>Idealne połączenie fachowców i potrzebujących.</h3>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-6 well" name="Poszukuje">
      <h2>Poszukuję</h2>
      <p>Potrzebujesz pomocy? Potrzebujesz fachowca?</p>
      <p>Znajdź oferentów</p>

      <div class="input-group">
        <input type="text" class="form-control" placeholder="Szukaj fachowca">
        <span class="input-group-btn">
        <button class="btn btn-default" type="button"><span class="glyphicon glyphicon-search"></span></button>
          <button class="btn btn-default"><span class="glyphicon glyphicon-pencil"></span>Daj ogłoszenie</button>
      </span>
      </div><!-- /input-group -->
    </div>
    <div class="col-md-6 well" name="Oferuje">
      <h2>Oferuję</h2>
      <p>Świadczysz usługi? Chciałbyś dorobić?</p>
      <p>Znajdź potrzebujących</p>

      <div class="input-group">
        <input type="text" class="form-control" placeholder="Szukaj potrzebujących">
        <span class="input-group-btn">
        <button class="btn btn-default" type="button"><span class="glyphicon glyphicon-search"></span></button>
          <button class="btn btn-default"><span class="glyphicon glyphicon-pencil"></span>Daj ogłoszenie</button>
      </span>
      </div><!-- /input-group -->
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<li>
  <%= user.id %>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    <%= link_to "delete", user, method: :delete, data: { confirm: "Are you sure?"} %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Aktualizuj swoje dane") %>
<h1>Zmiana danych</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= bootstrap_form_for(@user, layout: :horizontal, label_col: "col-md-4", control_col: "col-md-8") do |f| %>

        <%= render 'shared/error_messages' %>

        <%= f.text_field :name %>

        <%= f.text_field :email %>

        <%= f.password_field :password %>

        <%= f.password_field :password_confirmation %>

        <%= f.submit "Save changes", class: "btn btn-large btn-primary col-md-8 col-md-offset-4"  %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Użytkownicy') %>
<h1>All users</h1>

<%= will_paginate @users, renderer: BootstrapPagination::Rails %>

<ul class="users">
 <%= render @users %>
</ul>

<%= will_paginate @users, renderer: BootstrapPagination::Rails%>

app/views/users/new.html.erb
<% provide(:title, 'Rejestracja')%>
<h2>Rejestracja</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= bootstrap_form_for(@user, layout: :horizontal, label_col: "col-md-4", control_col: "col-md-8") do |f| %>

        <%= render 'shared/error_messages' %>

        <%= f.text_field :name %>

        <%= f.text_field :email %>

        <%= f.text_field :ulica %>

        <%= f.text_field :numer_domu %>

        <%= f.text_field :numer_mieszkania %>

        <%= f.text_field :kod_pocztowy %>

        <%= f.text_field :miasto %>

        <%= f.text_field :telefon %>

        <%= f.password_field :password %>

        <%= f.password_field :password_confirmation %>

        <%= f.submit "Utwórz konto", class: "btn btn-large btn-primary col-md-8 col-md-offset-4" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section>
      <h1><%= gravatar_for @user %></h1>
      <h1><%= @user.name %></h1>
      <h1><%= @user.email %></h1>
      <h1><%= @user.telefon %></h1>
      <h1><%= @user.ulica %></h1>
      <h1><%= @user.numer_domu %></h1>
      <h1><%= @user.numer_mieszkania %></h1>
      <h1><%= @user.kod_pocztowy %></h1>
      <h1><%= @user.miasto %></h1>

    </section>
  </aside>
</div>